"""Configurations for the RC car"""

PICAMERA_RESOLUTION_WIDTH = 640
PICAMERA_RESOLUTION_HEIGHT = 480
PICAMERA_RESOLUTION = (PICAMERA_RESOLUTION_WIDTH, PICAMERA_RESOLUTION_HEIGHT)
PICAMERA_FRAMERATE = 60
PICAMERA_WARM_UP_TIME = 2
INITIAL_TIME_SLEEP = 0.1

LEFT_MOTOR_DATA_ONE = 11
LEFT_MOTOR_DATA_TWO = 12
LEFT_MOTOR_ENABLE_PIN = 31
RIGHT_MOTOR_DATA_ONE = 13
RIGHT_MOTOR_DATA_TWO = 15
RIGHT_MOTOR_ENABLE_PIN = 32
#MOTOR_ENABLE_PIN = 31
PWM_FREQUENCY = 50
INITIAL_PWM_DUTY_CYCLE = 100

CLASSIFICATION_LABELS = ['forward', 'reverse', 'left', 'right', 'idle']
CLASSIFICATION_LABELS_AND_VALUES = {
    'forward': [1, 0, 0, 0, 0],
    'reverse': [0, 1, 0, 0, 0],
    'left': [0, 0, 1, 0, 0],
    'right': [0, 0, 0, 1, 0],
    'idle': [0, 0, 0, 0, 1]
}


IMAGE_DIMENSIONS = (75, 75)
LAMBDA = 0.1
HIDDEN_LAYER_SIZE = 100
